version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: todo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: todo-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://todo_user:secretpassword@db:5432/tododb
    command: uvicorn main_fastapi:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data: