name: CI Pipeline for FastAPI

on:
    push:
        branches: ["master"]  # Sadece main branch'e push olduğunda çalışır
    pull_request:
        branches: ["master"]  # veya PR açıldığında
    
jobs:
    test-and-build:
        runs-on: ubuntu-latest  # GitHub'ın sağladığı Linux ortam
    
        services:
          postgres:
            image: postgres:15
            env:
              POSTGRES_USER: todo_user
              POSTGRES_PASSWORD: secretpassword
              POSTGRES_DB: testdb
            ports:
              - 5432:5432
            options: >-
              --health-cmd "pg_isready"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    
        env:
          DATABASE_URL: postgresql://todo_user:secretpassword@localhost:5432/testdb
    
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3
    
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: 3.10
    
          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pytest
    
          - name: Run Tests
            run: |
              pytest --disable-warnings --maxfail=1
    
          - name: Build Docker Image
            run: |
              docker build -t fastapi-todo-app .
    
    